version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: social-media
    profiles: ["backend"]
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://variable:HxH787898HxH@hunter.com@sm-database:5432/sm-db
    networks:
      - social-media
    volumes:
      - ./.env:/app/.env
    depends_on:
      - sm-redis
      - sm-s3
      - db
  sm-redis:
    image: redis
    container_name: sm-redis-store
    restart: always
    ports:
      - "6380:6379"
    networks:
      - social-media
    profiles: ["backend"]
    volumes:
      - sm-redis_data:/data
    command: redis-server --appendonly yes
  sm-s3:
    image: 'bitnami/minio:latest'
    container_name: sm-s3-store
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: always
    environment:
      - MINIO_ROOT_USER=ROOTNAME
      - MINIO_ROOT_PASSWORD=CHANGEME123
    profiles: ["backend"]
    networks:
      - social-media
    volumes:
      - sm-s3:/data
  db:
    image: postgres
    container_name: sm-database
    networks:
      - social-media
    profiles: ["backend"]
    restart: always
    environment:
      - POSTGRES_PASSWORD=HxH787898HxH@hunter.com
      - POSTGRES_USER=variable
      - POSTGRES_DB=sm-db

networks:
  social-media:
    driver: bridge

volumes:
  sm-s3:
  sm-redis_data: